blueprint:
  name: Notification for Open Window and Low Temperature
  description: |
    This blueprint triggers a notification when:
    - The indoor temperature falls below a specified threshold.
    - At least one window or opening is open.
    - The outdoor temperature is lower than the indoor temperature.
    Use this to stay informed and avoid unnecessary energy loss.

  domain: automation

  input:
    inside_temperature_sensor:
      name: Indoor Temperature Sensor
      description: Select the sensor that monitors indoor temperature.
      selector:
        entity:
          domain: sensor

    outside_temperature_sensor:
      name: Outdoor Temperature Sensor
      description: Select the sensor that monitors outdoor temperature.
      selector:
        entity:
          domain: sensor

    window_sensors:
      name: Window or Opening Sensors
      description: Select one or more binary sensors monitoring windows or other openings. 
                   The notification will trigger if any of these are open.
      selector:
        target:
          entity:
            domain: binary_sensor
            device_class: opening

    temperature_threshold:
      name: Indoor Temperature Threshold
      description: If the indoor temperature falls below this value, 
                   the notification will trigger (if other conditions are also met).
      default: 18
      selector:
        number:
          min: -10
          max: 30
          unit_of_measurement: °C
          mode: box

trigger:
  - platform: state
    entity_id: !input inside_temperature_sensor

condition:
  - condition: numeric_state
    entity_id: !input inside_temperature_sensor
    below: !input temperature_threshold

  - condition: template
    value_template: >
      {% set outside_temp = states(input.outside_temperature_sensor.entity_id) | float %}
      {% set inside_temp = states(input.inside_temperature_sensor.entity_id) | float %}
      {{ outside_temp < inside_temp }}

  - condition: template
    value_template: >
      {{ expand(input.window_sensors.entity_id) | selectattr('state', 'eq', 'on') | list | length > 0 }}

action:
  - service: persistent_notification.create
    data:
      title: "Warning: Open Window and Cold Inside!"
      message: >
        The indoor temperature is {{ states(input.inside_temperature_sensor.entity_id) }}°C,
        at least one window or opening is open, and it's even colder outside!

mode: single
